package ex01

import (
	json "encoding/json"
	"testing"
)

const jsonString string = `
{
	"field0": true,
	"field1": -87253679,
	"field2": "id laborenon est velitincididuntsunt commodo ut nisi fugiatquis aliquased Duis veniamet Excepteurdolor ullamco",
	"field3": [
	  false,
	  false,
	  false,
	  false,
	  false,
	  false,
	  false,
	  false,
	  true,
	  false,
	  true,
	  true,
	  false,
	  true,
	  false,
	  false,
	  true,
	  false,
	  false,
	  true,
	  false,
	  false,
	  true,
	  true,
	  true,
	  false,
	  true,
	  true,
	  true,
	  true,
	  false,
	  true,
	  true,
	  true,
	  false,
	  true,
	  true,
	  false,
	  true,
	  true,
	  true,
	  false,
	  false,
	  false,
	  false,
	  true,
	  false,
	  false,
	  false,
	  true,
	  true,
	  true,
	  true,
	  false,
	  false,
	  false,
	  true,
	  true,
	  false,
	  true,
	  false,
	  false,
	  true,
	  false,
	  false,
	  true,
	  true,
	  false,
	  false,
	  false,
	  false,
	  false,
	  true,
	  false,
	  false,
	  true,
	  true,
	  false,
	  true,
	  true,
	  false,
	  true,
	  false,
	  false,
	  true,
	  false,
	  false,
	  true,
	  false,
	  true,
	  false,
	  true,
	  false,
	  false,
	  false,
	  false,
	  false,
	  true,
	  false,
	  false,
	  true,
	  false,
	  true,
	  true
	],
	"field4": [
	  90321817,
	  -9520120,
	  81277966,
	  6610187,
	  -26149535,
	  -60324172,
	  74025148,
	  16628725,
	  17571256,
	  -39597477,
	  15518899,
	  80355880,
	  -30728786,
	  -24507600,
	  -3875312,
	  -35797289,
	  -3707011,
	  35846027,
	  78455362,
	  7843050,
	  -8088301,
	  46659602,
	  -32788039,
	  -71309971,
	  81765685,
	  56015083,
	  -84460394,
	  -9417478,
	  10214928,
	  -46181345,
	  -58825359,
	  61778107,
	  71626160,
	  -29903418,
	  -79739755,
	  -89766638,
	  47585586,
	  -96705952,
	  -68062885,
	  11528042,
	  70745266,
	  31654892,
	  5169076,
	  97535135,
	  37169527,
	  58020397,
	  61950444,
	  58157780,
	  44958242,
	  97458730,
	  74126664,
	  -91135986,
	  52719208,
	  5821964,
	  -11602192,
	  60727906,
	  -90029778,
	  64060427,
	  -62404230,
	  20359056,
	  -21829702,
	  95073548,
	  86668285,
	  84814980,
	  -68220508,
	  -65629848,
	  4539877,
	  7769397,
	  53413470,
	  13734007,
	  62399956,
	  -53608781,
	  48889565,
	  -66973274,
	  90786381,
	  -76105471,
	  51023308,
	  71936720,
	  86460275,
	  45574365,
	  -1188700,
	  -64730226,
	  73467511,
	  -58357380,
	  -622019,
	  40445470,
	  13770222,
	  86690121,
	  53430765,
	  -78804688,
	  28554374,
	  70645749,
	  73346230,
	  86877853,
	  95148135,
	  -41438973,
	  -19592046,
	  -84623408,
	  33473933,
	  -37083471,
	  17465211,
	  36501638,
	  47434987,
	  30430786,
	  -22125266
	],
	"field5": [
	  "consectetur aute mollitanimculpaoccaecatadipisicing ad cupidatat Utdeserunt Lorem ad eiusmod estnulla est dolor ea dolor",
	  "eiusmod minim magna esse cupidatateiusmod cupidatat sit doloroccaecat Ut elit eadolor consecteturesse anim magna cillum ipsum",
	  "temporullamco dolore aute Lorem exercitationet quis deserunt consecteturveniam in nisi mollit aliqua",
	  "occaecat officia mollit irure exercitationin aliquain amet aliquip eiusmod auteid aute fugiat estex cillum Ut aute",
	  "dolor tempor ad Loremeu sunt in Excepteur consequatin fugiat aliqua cillum eiusmodinincupidatatconsectetur incididunt mollit",
	  "aute magnamagna sed sitadipisicingex tempor suntesse quispariatur inindolorein eiusmod sunt Utofficia",
	  "proident elit do voluptate minimexercitation Ut autealiquip fugiat irure sitmollit sunt estmagna esse in amet",
	  "ut doloreconsequat ex laboredeserunt culpa laborumDuis eiusmod esse adipisicingdolor irure ut cillum Lorem",
	  "eu commodoconsectetur aliquip occaecatmagna aliqua incididunteiusmod est labore adconsectetur dolore minim",
	  "ad aliquip consequatvelit Excepteur reprehenderitea officia doloret esse inmollitexercitation Duis laborum reprehenderit ut",
	  "ad commodo Excepteur dolor aliquain quis sintdooccaecat estin dolore sedUt consequat laboreeiusmod ut",
	  "tempor fugiat Utcupidatatdolorex eiusmod Ut irureExcepteur ut Duis reprehenderitidin nonquis ullamco",
	  "occaecat nonmollit dolor Lorem voluptate fugiatconsequat laborum proident exdolor consecteturofficia tempor adipisicing occaecat",
	  "sitquis in sintdolore fugiat tempor donon cillum nostrud irureinLorem sed ullamco exdolor ut magna exercitation",
	  "ipsumnon culpa ex ullamcoirure consequatirureeiusmod ex nostrud ipsumtemporcillum Duis commodo officia",
	  "qui exercitation est cillum culpaquis cupidatat laboriseadolore in cupidatat voluptateExcepteur ea in Lorem irure",
	  "quistempor commodoin officia exercitationaute ut et irurevoluptate exercitation utdolore laborumcillum laborum sed",
	  "sed aliquip ut ad consequatoccaecat amet dolorein non dolorpariaturad ea tempor officia deseruntdolor veniam incididunt",
	  "fugiat esse dolorcillum minim Excepteur nonut eamagna commodo Ut eu adipisicingquissed ullamco do consequat veniam",
	  "siteu fugiataute in Lorem incididunt ipsumaute ex officia consectetur utmollit aliquip pariatur veniam aliqua",
	  "deserunt etUt quis ad velitlaborum aute nostrudnon ex adipisicing nisivelit nostrud enimeuqui nonLorem nisi voluptate ipsum esse",
	  "veniamreprehenderit sit tempor velitlaborein doconsequat nostrudin voluptate cillum dolore nullaex sint",
	  "ut magna adipisicing dolorenulla sint in temporut cillum eiusmodminimnostrudiddolor amet consequatesse elit",
	  "officia aute irure velit Utmollitsintdolor enimsit elitreprehenderit do sintexDuis tempor magnaeiusmod elit consectetur ipsum",
	  "Ut qui voluptate utdo mollit elit utipsumdolor in labore commodo magnaaliquaexercitation consectetur cillum",
	  "laboris minimadipisicing mollit nulla officiaenim id reprehenderit minim culpaqui cupidatatmollit amet sed",
	  "Loremfugiat ipsum nondolor in eiusmodcommodo nisi doloreea et cillum aute voluptateproidentExcepteur deserunt non exercitation",
	  "in sedeu exercitation Ututea minim laboris animreprehenderit deserunt officia velit nullacommodo non mollit ex",
	  "incididunt dolorein est cupidatat Ut quissint laborum irure ut eiusmoddeserunt eu et ametexercitation in aute",
	  "ad laboris ex officiaipsumdolor deseruntvelit elit veniam fugiatin irure velit do officiaadipisicing in",
	  "culpa ut occaecat Loremoccaecat ullamconisi aute sintDuis reprehenderit sunt laboreea eiusmod mollit ipsum",
	  "Duis tempor quiseiusmodminim eu adipisicingetlabore eulaboris incididunt dolore officia cillumnisi aliqua",
	  "labore Lorem eu cupidatat exest commodoirurecillumipsum laborum dolor quimagnasunt commodo ut magna veniam",
	  "irurequi ipsumipsum voluptate et aliquacommodo dolorsit fugiat commodoenim velit eu nullafugiat cupidatat",
	  "proident quisuntconsectetur pariatur amet cillum eiusmodnullanulla consecteturconsequat proidentaute ut nisi",
	  "anim veniamexercitation consequat idmagna euquis eiusmod deserunt reprehenderitExcepteur sint proident",
	  "sunt magnaqui ullamco insintlaboris minim ut ipsumnisialiqua nostrud do Lorem eaexercitation nulla commodo in cillum",
	  "idut commododolor non veniam anim irureirureveniam velit mollit do elitsitex culpa utsit amet eiusmod et",
	  "et proident ex eiusmodetexercitation quis mollit doloredeserunt incididunt sedvelit consequat officia pariatur aliquip",
	  "aliquipex ut quisconsectetur sint quis incididuntdoloreadipisicing qui incididunt in dolordolor occaecat esse",
	  "pariaturet in occaecat aliquiput laboris ipsum eiusmod fugiatdoloreesse in officia deserunt adirure est ullamco Lorem enim",
	  "laborum exercitation Duis suntDuis eiusmod sit insed elitcillum aliquip voluptate consectetur laboris",
	  "laborum est nulla esse quisproident dolornulla nisi magna aliquipsitexercitationLorem cupidatatveniam consectetur sunt",
	  "mollit sit nisi labore exUt est amet doloredolor deserunt occaecat ut proidentesse magna nisi consectetur culpa",
	  "dolore laborepariatur consequat voluptateut fugiatqui id aliquipelit in dolorExcepteur nulla aliquip sunt",
	  "minim Excepteur qui laborelaboris cupidatat voluptate nostrudminimculpa Duis cupidatat Lorempariatur ut",
	  "sed aute adipisicing cillumnon ut ea sednulla nostrudsed voluptate tempor commodo quisenim mollit irure exercitation",
	  "dolor ipsumid ipsum ut laboreconsectetur occaecat id sunteu aute consectetur tempormagna dolore sit do",
	  "nisi incididunt doest ipsumut eiusmod magna in DuisLorem nostrud Duis proident velitexercitation pariatur",
	  "ullamcoullamcoipsum aliquip ametin tempor utcommododoloreeiusmod Duis id UtDuis cupidatat autevoluptate cupidatat aliqua Excepteur",
	  "consequat enim ea in Duisdoveniamanim ad incididunt mollit sitqui Duisirure sint aliquipDuis aute veniam sint",
	  "occaecat commodo Duiscommodo ut cupidatat nisi irureconsectetur irure elit anim proidentcommodo exercitation do Duis eu",
	  "nulla fugiat et culpa laboreid magna esse et consecteturcillum ad amet dolore sedpariatur enim minim culpa eu",
	  "voluptate labore et nostrudsit adipisicingadipisicingofficia sunt Duisvelitsunt enim dosit dolordolor velit aute",
	  "reprehenderitsed reprehenderit laboreullamco fugiat sint nullaquis cillum in Lorem doloreenim anim magna",
	  "aute voluptate adipisicingnon consectetur ex fugiat eiusmodpariatur ipsum nostrud doloreanim deserunt et",
	  "sed sint irure veniamUt aute proident Excepteur elitpariatur ipsum aliquip insed sit elitcupidatat anim",
	  "pariatur culpacillum cupidatat Ut magna exeiusmodirure Excepteurin quis est adipisicingdeseruntadipisicing dolore mollit ea elit",
	  "ullamco laboris in cupidatatnisi laborum quis aliquaenim dolor culpa pariatur utin aliquacommodo officia in in",
	  "cupidatat in minimminim commodo consequat eu nisidolor reprehenderit magnasunt dolor incididunt magna do",
	  "sed nostrud exercitationea cupidatat nisi ipsum velitirureincididunt dolor dolorein eudeserunt Duislaborum",
	  "id est commodo minimqui dolor ipsum ullamco utExcepteur pariatur nonincididunt inminim dolor aliquado veniam in fugiat Ut",
	  "in sint consequat doloread nisitempor esse qui nisi laborumexercitation culpa minim do adipisicingin labore occaecat dolor",
	  "nulla doaute adipisicingut ut in voluptate aliquanon sint aliquipnulla in sed Ut adipisicingenim commodo nulla elit",
	  "id fugiat laborumdolore est ex ipsum utdolormollit Duis ex utUt nostrud in doloreconsequatLorem nisi ad",
	  "dolormagnaullamcominimnon ad quis est fugiataute cupidatatproident magna in exercitation incididuntnostrud irure ut laboris",
	  "Ut fugiat consequat idsuntet nostrud minim utveniam Ut fugiat ipsumproident Ut exercitation consequat ipsum",
	  "dolore quis Utculpa laboris ipsum in minimreprehenderit dolor voluptate dolor irureirure proident Excepteur",
	  "non fugiat inLorem dolor amet sed dolorein adipisicing dolore aliquiplabore commodo fugiat deserunt in",
	  "amet eu aliqua Utdoloreullamco in laborumtempor minim ametfugiat et cillumconsequat ad nulla qui dolor",
	  "in ad dolorest veniamqui tempor ipsumdeserunt veniamsed quis pariatur irureadipisicing tempor voluptate irure sint",
	  "pariatur doad laborisea esse magnaproident in tempor laborumnon incididunt minimdolore enim inamet irure",
	  "aute ea ad deserunteiusmod aliqua adipisicingdolor eiusmodid culpa consequatexercitation irure ipsum aliquip est",
	  "esse dolorexUt est ullamco deserunt quinondo sit voluptatequisea deserunt culpa do suntfugiat ut voluptate eu",
	  "do exaliquaUt ut aute eu reprehenderitnulla do dolor et adipisicingproidentut velitmagna tempor sed Lorem",
	  "dolore labore do nostrud animdolor tempor quis cupidatatsunt officia enimlaboris nulla deserunt do reprehenderit",
	  "minim consectetur veniam non temporculpa consectetur esse in utproident tempor ullamco estutproident dolor",
	  "aliqua dolorereprehenderit labore cupidatat pariaturpariatur exercitation anim non ipsumnostrud sed cupidatat dolore",
	  "adipisicing non ullamcocillumin mollit nostrud amet consequatofficia elit occaecat cupidatataliqua sint ad et consectetur",
	  "do anim Duis Excepteurin deseruntaliquip sunt officia adipisicinglaboris eiusmod cillum non aliquipeiusmod",
	  "in do exercitation ad sitdolore nisiin laborisin cillum laborum fugiatea doqui aliquaet ex sit esse laboris",
	  "labore magna dolor nisi laborumut officia laborum minim sedsit enim Duis laboredoirure aliquip ipsum",
	  "dolore culpaDuis nostrudea Lorem in cillum elitExcepteur sunt ullamcoeiusmod deserunt inLorem cillum consequat ad",
	  "nisi nostrud consequat Ut enimcupidatattempor sit aute aliquacupidatat cillum Excepteur ut ullamcodolor exercitation et fugiat",
	  "cillum siteu quis Excepteurin veniam voluptatefugiat aliquipquis commodo qui proidentnulla cillumaute Excepteur",
	  "sunt exercitation voluptate magna inesse quis Lorem in nostrudDuis laborisdolor aliqua est anim cillum",
	  "nisi eiusmod cupidatatad Loremsed nostrud velit incididunt quisconsequat mollit id dolorelaboresed ut Ut",
	  "euLorem in non aute eudolore dolor mollit non occaecatenim cupidatat irure nostrudid exercitation fugiat proident",
	  "sedin nulla proidentsunt Excepteur dolorut quireprehenderit amet nostrud veniamlaborum sedenim commodo",
	  "quis esse eu cupidatatanim cupidatat exercitationnostrud elit doloreamet commodoin in aute nulla exercitation",
	  "proident occaecat adipisicing quisquifugiat ea magnaesse aliquip consectetur sunt magnainullamco veniam ad",
	  "ut culpa magnaea eiusmod adminim esse velit pariatur cillumin deserunt amet quiLoremauteexercitation consectetur in esse nulla",
	  "ut nostrud veniam proident autenostrud laborum aliqualaborumofficia dolor et eiusmodelitaliqua consectetur ullamco sunt",
	  "adipisicing labore dolore ut consecteturenim sed sint culpa utmollitin cupidatatelitlaboreex officia",
	  "ex mollit aliquamollitdoofficia ipsum nulla Duisid eiusmod amet sit doloramet veniam quiadipisicingad consequat aute fugiat in",
	  "esttempor et officia pariaturinnostrud incididunt commodo culpa occaecatminim ullamco in cillumnostrud officia cupidatat anim",
	  "in ullamco eapariatur utveniam dolorein id dolor pariatur utvelit idcupidatat proident Loremanim elit dolor culpa tempor",
	  "adipisicing veniam voluptate fugiat mollitea est quis laborumin qui magna ad deseruntet cupidatat elit adipisicing velit",
	  "dolore dolor adipisicingdolore Duisvoluptate non sed amet adreprehenderit UtUt anim Lorem culpa fugiat",
	  "exercitationlabore minimut officiaadipsum anim occaecatad temporreprehenderit aliquipDuis exconsectetur veniam Excepteur laboris Duis",
	  "voluptate ea fugiatea dolore laboris veniamdolor sedipsum eu deserunt id nostruddo dolore eu incididunt culpa"
	]
  }
`

func BenchmarkSample(b *testing.B) {
	e := &Example{}
	jsonBytes := []byte(jsonString)
	b.ReportAllocs()
	b.Run("Easy JSON", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			e.UnmarshalJSON(jsonBytes)
		}
	})
	b.Run("Standard JSON", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			json.Unmarshal([]byte(jsonBytes), e)
		}
	})
}
