#!/usr/bin/env bash

docker run -it --rm -p 3999:3999 -p 9000:9000 -v $(pwd):/app -v $(pwd)/theme/static:/go/src/golang.org/x/tools/cmd/present/static -v $(pwd)/theme/templates:/go/src/golang.org/x/tools/cmd/present/templates litleleprikon/present -http=0.0.0.0:3999 -orighost=localhost -notes # -base theme